{
  "branches": ["main"],
  "plugins": [
    "@semantic-release/exec",
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "CHANGELOG.md"
      }
    ],
    [
      "@google/semantic-release-replace-plugin",
      {
        "replacements": [
          {
            "files": ["pom.xml"],
            "from": "<version>.*</version><!-- ms-version -->",
            "to": "<version>${nextRelease.version}</version><!-- ms-version -->",
            "results": [
              {
                "file": "pom.xml",
                "hasChanged": true,
                "numMatches": 1,
                "numReplacements": 1
              }
            ],
            "countMatches": true
          }
        ]
      }
    ],
    [
      "@semantic-release/git",
      {
        "assets": ["CHANGELOG.md", "pom.xml"]
      }
    ],
    "@semantic-release/github"
  ]
}
